# Generated by Django 4.0.2 on 2022-04-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrataciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
