# Generated by Django 4.0.2 on 2022-03-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agrupacion',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
