# Generated by Django 4.0.2 on 2022-04-28 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255)),
                ('agrupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agrupaciones.agrupacion')),
            ],
        ),
    ]
