# Generated by Django 4.0.2 on 2022-02-21 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrupaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=255)),
                ('agrupacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agrupaciones.agrupacion')),
            ],
        ),
    ]
